/**
 * Definition for singly-linked list.
 * struct ListNode {
 *     int val;
 *     ListNode *next;
 *     ListNode() : val(0), next(nullptr) {}
 *     ListNode(int x) : val(x), next(nullptr) {}
 *     ListNode(int x, ListNode *next) : val(x), next(next) {}
 * };
 */
class Solution {
public:
    ListNode* middleNode(ListNode* head) {
        ListNode* x = head;
        ListNode* y = head;
        if(head==NULL) 
        return NULL;
        
        else
        {
        while(x!=NULL and x->next!=NULL)
        {
            x = x->next->next;
             y = y->next;
        }
           
            return y;
    }
    }
};
